//source signature: [DE-73-AD-8B-D0-C0-C3-D1-79-25-52-7D-EA-09-09-3A]
// Autogenerated at 2016/3/24 14:25:36.
// Created by [CodeGenerator Library:1.7.3.2014.04.20.15.19] FOR Server Protocol.
// Don't manully change this code unless you have to, all changes will be lost next time code is generated.
// Copyright ideadynamo.com 2008.
namespace com.tieao.mmo.deamon.server
{
    using System;
    using System.Text;
    using System.Xml;
    using System.IO;
    using System.Collections;
    using System.Collections.Generic;
    using com.ideadynamo.foundation;
    using com.ideadynamo.foundation.buffer;
    using com.tieao.mmo.deamon;
    
    // set com.tieao.mmo.deamon
    /*Reference Codes
    
    [Serializable]
    public class WorldState
    {
      public int timestamp;
      public int logons;
      public float sdkresponse;
      public int refills;
      public int refilltotal;
      public int serials;
      public int lastlogontime;
      public int newusers;
      

      public void WriteToByteArray(ByteArray byteArray)
      {
        byteArray.writeDynamicsInt( timestamp);
        byteArray.writeDynamicsInt( logons);
        byteArray.writeFloat( sdkresponse);
        byteArray.writeDynamicsInt( refills);
        byteArray.writeDynamicsInt( refilltotal);
        byteArray.writeDynamicsInt( serials);
        byteArray.writeDynamicsInt( lastlogontime);
        byteArray.writeDynamicsInt( newusers);
        
      }

      public void ReadFromByteArray(ByteArray byteArray)
      {
        timestamp = byteArray.readDynamicsInt();
        logons = byteArray.readDynamicsInt();
        sdkresponse = byteArray.readFloat();
        refills = byteArray.readDynamicsInt();
        refilltotal = byteArray.readDynamicsInt();
        serials = byteArray.readDynamicsInt();
        lastlogontime = byteArray.readDynamicsInt();
        newusers = byteArray.readDynamicsInt();
        
      }
      
      public static WorldState SReadFromByteArray(ByteArray byteArray)
      {
          WorldState elem = new WorldState ();
          elem.ReadFromByteArray(byteArray);
          return elem;
      }
      
      
      public override string ToString()
      {
          StringBuilder sb = new StringBuilder();
          sb.Append("WorldState:{");
          
          sb.AppendFormat(@" timestamp  = ""{0}"",",timestamp );
          
          sb.AppendFormat(@" logons  = ""{0}"",",logons );
          
          sb.AppendFormat(@" sdkresponse  = ""{0}"",",sdkresponse );
          
          sb.AppendFormat(@" refills  = ""{0}"",",refills );
          
          sb.AppendFormat(@" refilltotal  = ""{0}"",",refilltotal );
          
          sb.AppendFormat(@" serials  = ""{0}"",",serials );
          
          sb.AppendFormat(@" lastlogontime  = ""{0}"",",lastlogontime );
          
          sb.AppendFormat(@" newusers  = ""{0}"",",newusers );
          
          sb.Remove(sb.Length - 1, 1);
          sb.Append("}");
          return sb.ToString();
      }
  }
  
    [Serializable]
    public class VillageState
    {
      public int timestamp;
      public int logons;
      public float logonresponse;
      public int paymenttoday;
      

      public void WriteToByteArray(ByteArray byteArray)
      {
        byteArray.writeDynamicsInt( timestamp);
        byteArray.writeDynamicsInt( logons);
        byteArray.writeFloat( logonresponse);
        byteArray.writeDynamicsInt( paymenttoday);
        
      }

      public void ReadFromByteArray(ByteArray byteArray)
      {
        timestamp = byteArray.readDynamicsInt();
        logons = byteArray.readDynamicsInt();
        logonresponse = byteArray.readFloat();
        paymenttoday = byteArray.readDynamicsInt();
        
      }
      
      public static VillageState SReadFromByteArray(ByteArray byteArray)
      {
          VillageState elem = new VillageState ();
          elem.ReadFromByteArray(byteArray);
          return elem;
      }
      
      
      public override string ToString()
      {
          StringBuilder sb = new StringBuilder();
          sb.Append("VillageState:{");
          
          sb.AppendFormat(@" timestamp  = ""{0}"",",timestamp );
          
          sb.AppendFormat(@" logons  = ""{0}"",",logons );
          
          sb.AppendFormat(@" logonresponse  = ""{0}"",",logonresponse );
          
          sb.AppendFormat(@" paymenttoday  = ""{0}"",",paymenttoday );
          
          sb.Remove(sb.Length - 1, 1);
          sb.Append("}");
          return sb.ToString();
      }
  }
  
    [Serializable]
    public class PortalState
    {
      public int timestamp;
      public int logons;
      public float logonresponse;
      

      public void WriteToByteArray(ByteArray byteArray)
      {
        byteArray.writeDynamicsInt( timestamp);
        byteArray.writeDynamicsInt( logons);
        byteArray.writeFloat( logonresponse);
        
      }

      public void ReadFromByteArray(ByteArray byteArray)
      {
        timestamp = byteArray.readDynamicsInt();
        logons = byteArray.readDynamicsInt();
        logonresponse = byteArray.readFloat();
        
      }
      
      public static PortalState SReadFromByteArray(ByteArray byteArray)
      {
          PortalState elem = new PortalState ();
          elem.ReadFromByteArray(byteArray);
          return elem;
      }
      
      
      public override string ToString()
      {
          StringBuilder sb = new StringBuilder();
          sb.Append("PortalState:{");
          
          sb.AppendFormat(@" timestamp  = ""{0}"",",timestamp );
          
          sb.AppendFormat(@" logons  = ""{0}"",",logons );
          
          sb.AppendFormat(@" logonresponse  = ""{0}"",",logonresponse );
          
          sb.Remove(sb.Length - 1, 1);
          sb.Append("}");
          return sb.ToString();
      }
  }
  
    [Serializable]
    public class UpdaterState
    {
      public int timestamp;
      public string andoirdapp;
      public string andoirdres;
      public string iosapp;
      public string iosres;
      

      public void WriteToByteArray(ByteArray byteArray)
      {
        byteArray.writeDynamicsInt( timestamp);
        byteArray.writeUTF( andoirdapp);
        byteArray.writeUTF( andoirdres);
        byteArray.writeUTF( iosapp);
        byteArray.writeUTF( iosres);
        
      }

      public void ReadFromByteArray(ByteArray byteArray)
      {
        timestamp = byteArray.readDynamicsInt();
        andoirdapp = byteArray.readUTF();
        andoirdres = byteArray.readUTF();
        iosapp = byteArray.readUTF();
        iosres = byteArray.readUTF();
        
      }
      
      public static UpdaterState SReadFromByteArray(ByteArray byteArray)
      {
          UpdaterState elem = new UpdaterState ();
          elem.ReadFromByteArray(byteArray);
          return elem;
      }
      
      
      public override string ToString()
      {
          StringBuilder sb = new StringBuilder();
          sb.Append("UpdaterState:{");
          
          sb.AppendFormat(@" timestamp  = ""{0}"",",timestamp );
          
          sb.AppendFormat(@" andoirdapp  = ""{0}"",",andoirdapp );
          
          sb.AppendFormat(@" andoirdres  = ""{0}"",",andoirdres );
          
          sb.AppendFormat(@" iosapp  = ""{0}"",",iosapp );
          
          sb.AppendFormat(@" iosres  = ""{0}"",",iosres );
          
          sb.Remove(sb.Length - 1, 1);
          sb.Append("}");
          return sb.ToString();
      }
  }
  
    [Serializable]
    public class BattleState
    {
      public int timestamp;
      public string currentcount;
      public string maxcount;
      

      public void WriteToByteArray(ByteArray byteArray)
      {
        byteArray.writeDynamicsInt( timestamp);
        byteArray.writeUTF( currentcount);
        byteArray.writeUTF( maxcount);
        
      }

      public void ReadFromByteArray(ByteArray byteArray)
      {
        timestamp = byteArray.readDynamicsInt();
        currentcount = byteArray.readUTF();
        maxcount = byteArray.readUTF();
        
      }
      
      public static BattleState SReadFromByteArray(ByteArray byteArray)
      {
          BattleState elem = new BattleState ();
          elem.ReadFromByteArray(byteArray);
          return elem;
      }
      
      
      public override string ToString()
      {
          StringBuilder sb = new StringBuilder();
          sb.Append("BattleState:{");
          
          sb.AppendFormat(@" timestamp  = ""{0}"",",timestamp );
          
          sb.AppendFormat(@" currentcount  = ""{0}"",",currentcount );
          
          sb.AppendFormat(@" maxcount  = ""{0}"",",maxcount );
          
          sb.Remove(sb.Length - 1, 1);
          sb.Append("}");
          return sb.ToString();
      }
  }
  
    End Reference Codes*/
    #region Service And Interfaces
    
    internal class EnumMonitorMethods
    {
        
        public const int SERVER_QUERYSTATUS_HASH = 1921645312;
        public const int SERVER_EXECUTECOMMAND_HASH = -325838586;
        public const int CLIENT_STATUSREPORT_HASH = 1012794114;
        public const int CLIENT_SENDMESSAGE_HASH = 1289645117;
        public const int CLIENT_COMMANDRESULT_HASH = 1368138742;

        public const int CLIENT_REQUESTERROR_HASH = -322979391;
    }
    
    public class  MonitorServerHelper
    {
        public const string SOURCE_HASH = "DE-73-AD-8B-D0-C0-C3-D1-79-25-52-7D-EA-09-09-3A";

        
        public static ByteArray StatusReport(ByteArray status)
        {
            ByteArray byteArray = new ByteArray();
            
            byteArray.writeInt( EnumMonitorMethods.CLIENT_STATUSREPORT_HASH );
            byteArray.EncryptKey =  EnumMonitorMethods.CLIENT_STATUSREPORT_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
          status.WriteToByteArray(byteArray);
          
          ++ByteArray.globalSeq;
            byteArray.writeInt(byteArray.CRC);
            byteArray.EncryptKey =  0;
            return byteArray;
        }
        
        public static ByteArray SendMessage(string message)
        {
            ByteArray byteArray = new ByteArray();
            
            byteArray.writeInt( EnumMonitorMethods.CLIENT_SENDMESSAGE_HASH );
            byteArray.EncryptKey =  EnumMonitorMethods.CLIENT_SENDMESSAGE_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
          byteArray.writeUTF(message);
          
          ++ByteArray.globalSeq;
            byteArray.writeInt(byteArray.CRC);
            byteArray.EncryptKey =  0;
            return byteArray;
        }
        
        public static ByteArray CommandResult(string command,int result,string message)
        {
            ByteArray byteArray = new ByteArray();
            
            byteArray.writeInt( EnumMonitorMethods.CLIENT_COMMANDRESULT_HASH );
            byteArray.EncryptKey =  EnumMonitorMethods.CLIENT_COMMANDRESULT_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
          byteArray.writeUTF(command);byteArray.writeDynamicsInt(result);byteArray.writeUTF(message);
          
          ++ByteArray.globalSeq;
            byteArray.writeInt(byteArray.CRC);
            byteArray.EncryptKey =  0;
            return byteArray;
        }
        
        public static void StatusReport(ByteArray status,ByteArray  byteArray)
        {
            byteArray.Reset();
            byteArray.WriteHeader();
            
            byteArray.writeInt( EnumMonitorMethods.CLIENT_STATUSREPORT_HASH );
            byteArray.EncryptKey =  EnumMonitorMethods.CLIENT_STATUSREPORT_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
            status.WriteToByteArray(byteArray);
            ++ByteArray.globalSeq;
            byteArray.writeIntNCRC(byteArray.CRC);
            byteArray.EncryptKey =  0;
        }
        
        public static void SendMessage(string message,ByteArray  byteArray)
        {
            byteArray.Reset();
            byteArray.WriteHeader();
            
            byteArray.writeInt( EnumMonitorMethods.CLIENT_SENDMESSAGE_HASH );
            byteArray.EncryptKey =  EnumMonitorMethods.CLIENT_SENDMESSAGE_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
            byteArray.writeUTF(message);
            ++ByteArray.globalSeq;
            byteArray.writeIntNCRC(byteArray.CRC);
            byteArray.EncryptKey =  0;
        }
        
        public static void CommandResult(string command,int result,string message,ByteArray  byteArray)
        {
            byteArray.Reset();
            byteArray.WriteHeader();
            
            byteArray.writeInt( EnumMonitorMethods.CLIENT_COMMANDRESULT_HASH );
            byteArray.EncryptKey =  EnumMonitorMethods.CLIENT_COMMANDRESULT_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
            byteArray.writeUTF(command);byteArray.writeDynamicsInt(result);byteArray.writeUTF(message);
            ++ByteArray.globalSeq;
            byteArray.writeIntNCRC(byteArray.CRC);
            byteArray.EncryptKey =  0;
        }
        
        public static ByteArray ClientRequestFailed__(int reason)
        {
            ByteArray byteArray = new ByteArray();
            byteArray.writeInt( EnumMonitorMethods.CLIENT_REQUESTERROR_HASH);
            byteArray.EncryptKey =  EnumMonitorMethods.CLIENT_REQUESTERROR_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
            byteArray.writeDynamicsInt(reason);
            ++ByteArray.globalSeq;
            byteArray.writeIntNCRC(byteArray.CRC);
            byteArray.EncryptKey =  0;
            return byteArray;
        }

        public static bool IntepretMessage(ByteArray byteArray,IMonitorServerService serverService)
        {
            byteArray.BypassHeader();
            int methodID = byteArray.readInt();
            bool mtdrst__ = false;
            switch(methodID)
            {
              
              case EnumMonitorMethods.SERVER_QUERYSTATUS_HASH: 
              {
                  byteArray.EncryptKey = EnumMonitorMethods.SERVER_QUERYSTATUS_HASH;
                  byteArray.CRC = 0;
                  byteArray.readDynamicsInt();

                  mtdrst__ = OnQueryStatus(byteArray , serverService);
                  byteArray.EncryptKey =  0;
                  return mtdrst__;
              }
              
              case EnumMonitorMethods.SERVER_EXECUTECOMMAND_HASH: 
              {
                  byteArray.EncryptKey = EnumMonitorMethods.SERVER_EXECUTECOMMAND_HASH;
                  byteArray.CRC = 0;
                  byteArray.readDynamicsInt();

                  mtdrst__ = OnExecuteCommand(byteArray , serverService);
                  byteArray.EncryptKey =  0;
                  return mtdrst__;
              }
              
              case EnumMonitorMethods.CLIENT_REQUESTERROR_HASH:
                byteArray.EncryptKey =  EnumMonitorMethods.CLIENT_REQUESTERROR_HASH ;
                byteArray.readDynamicsInt();
                OnClientRequestError__(byteArray , serverService);
                byteArray.EncryptKey = 0;
                return true;
            }
            
            // recover the header
            byteArray.Rewind();
            return false;
        }

        public static String ParseMessage(ByteArray byteArray , ParamedDelegate<String> dumper)
        {
            byteArray.BypassHeader();
            int methodID = byteArray.readInt();
            String result = String.Empty;
            switch(methodID)
            {
            
            case EnumMonitorMethods.SERVER_QUERYSTATUS_HASH: 
                result = ParseQueryStatus(byteArray); 
                break;
            case EnumMonitorMethods.SERVER_EXECUTECOMMAND_HASH: 
                result = ParseExecuteCommand(byteArray); 
                break;               
            case EnumMonitorMethods.CLIENT_REQUESTERROR_HASH:
                byteArray.EncryptKey =  EnumMonitorMethods.CLIENT_REQUESTERROR_HASH ;
                byteArray.readDynamicsInt();
                int reason = byteArray.readDynamicsInt();
                byteArray.EncryptKey = 0;
                return string.Format("Client Request Error {0}" ,reason);
            }
            if(result != String.Empty) dumper(result);
            // recover the header
            byteArray.Rewind();
            return result;
        }

        
        private static bool OnQueryStatus(ByteArray byteArray,IMonitorServerService serverService)
        {
            int catagory = byteArray.readDynamicsInt();
            
            int crc = byteArray.readIntNCRC();
            if(crc == byteArray.CRC)
            {
            serverService.OnQueryStatus( catagory);
            }
            byteArray.Recycle();
            return true;
        }
        
        private static bool OnExecuteCommand(ByteArray byteArray,IMonitorServerService serverService)
        {
            String command = byteArray.readUTF();
            
            int crc = byteArray.readIntNCRC();
            if(crc == byteArray.CRC)
            {
            serverService.OnExecuteCommand( command);
            }
            byteArray.Recycle();
            return true;
        }
        
        private static bool OnClientRequestError__(ByteArray byteArray , IMonitorServerService serverService)
        {
            int errorCode = byteArray.readDynamicsInt();
            if(ClientRequestErrorHandler__ != null)
            {
                ClientRequestErrorHandler__(errorCode);
            }
            return true;
        }
        
        private static string ParseQueryStatus(ByteArray byteArray)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("QueryStatus(");
            
            sb.Append("catagory : int");
            
            sb.Append("){\r\n");
            int crc__ = byteArray.readIntNCRC(); // parse global seq
            int catagory = byteArray.readDynamicsInt();
            sb.AppendFormat(@"catagory = ""{0}""",  catagory);
            sb.Append("}");
            return sb.ToString();
        }
        
        private static string ParseExecuteCommand(ByteArray byteArray)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("ExecuteCommand(");
            
            sb.Append("command : string");
            
            sb.Append("){\r\n");
            int crc__ = byteArray.readIntNCRC(); // parse global seq
            String command = byteArray.readUTF();
            sb.AppendFormat(@"command = ""{0}""",  command);
            sb.Append("}");
            return sb.ToString();
        }
        
        
        public delegate void ClientRequestErrorDelegate__(int errorCode);
        public static ClientRequestErrorDelegate__ ClientRequestErrorHandler__;
   }

    public interface IMonitorServerService
    {
        void OnQueryStatus( int catagory);
        void OnExecuteCommand( string command);
        
    }
  
    internal class EnumWorldReportMethods
    {
        
        public const int CLIENT_REPORTSTATUS_HASH = -932721042;

        public const int CLIENT_REQUESTERROR_HASH = -232571275;
    }
    
    public class  WorldReportServerHelper
    {
        public const string SOURCE_HASH = "DE-73-AD-8B-D0-C0-C3-D1-79-25-52-7D-EA-09-09-3A";

        
        public static ByteArray ReportStatus(WorldState status)
        {
            ByteArray byteArray = new ByteArray();
            
            byteArray.writeInt( EnumWorldReportMethods.CLIENT_REPORTSTATUS_HASH );
            byteArray.EncryptKey =  EnumWorldReportMethods.CLIENT_REPORTSTATUS_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
          status.WriteToByteArray(byteArray);
          
          ++ByteArray.globalSeq;
            byteArray.writeInt(byteArray.CRC);
            byteArray.EncryptKey =  0;
            return byteArray;
        }
        
        public static void ReportStatus(WorldState status,ByteArray  byteArray)
        {
            byteArray.Reset();
            byteArray.WriteHeader();
            
            byteArray.writeInt( EnumWorldReportMethods.CLIENT_REPORTSTATUS_HASH );
            byteArray.EncryptKey =  EnumWorldReportMethods.CLIENT_REPORTSTATUS_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
            status.WriteToByteArray(byteArray);
            ++ByteArray.globalSeq;
            byteArray.writeIntNCRC(byteArray.CRC);
            byteArray.EncryptKey =  0;
        }
        
        public static ByteArray ClientRequestFailed__(int reason)
        {
            ByteArray byteArray = new ByteArray();
            byteArray.writeInt( EnumWorldReportMethods.CLIENT_REQUESTERROR_HASH);
            byteArray.EncryptKey =  EnumWorldReportMethods.CLIENT_REQUESTERROR_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
            byteArray.writeDynamicsInt(reason);
            ++ByteArray.globalSeq;
            byteArray.writeIntNCRC(byteArray.CRC);
            byteArray.EncryptKey =  0;
            return byteArray;
        }

        public static bool IntepretMessage(ByteArray byteArray,IWorldReportServerService serverService)
        {
            byteArray.BypassHeader();
            int methodID = byteArray.readInt();
            bool mtdrst__ = false;
            switch(methodID)
            {
              
              case EnumWorldReportMethods.CLIENT_REQUESTERROR_HASH:
                byteArray.EncryptKey =  EnumWorldReportMethods.CLIENT_REQUESTERROR_HASH ;
                byteArray.readDynamicsInt();
                OnClientRequestError__(byteArray , serverService);
                byteArray.EncryptKey = 0;
                return true;
            }
            
            // recover the header
            byteArray.Rewind();
            return false;
        }

        public static String ParseMessage(ByteArray byteArray , ParamedDelegate<String> dumper)
        {
            byteArray.BypassHeader();
            int methodID = byteArray.readInt();
            String result = String.Empty;
            switch(methodID)
            {
                           
            case EnumWorldReportMethods.CLIENT_REQUESTERROR_HASH:
                byteArray.EncryptKey =  EnumWorldReportMethods.CLIENT_REQUESTERROR_HASH ;
                byteArray.readDynamicsInt();
                int reason = byteArray.readDynamicsInt();
                byteArray.EncryptKey = 0;
                return string.Format("Client Request Error {0}" ,reason);
            }
            if(result != String.Empty) dumper(result);
            // recover the header
            byteArray.Rewind();
            return result;
        }

        
        private static bool OnClientRequestError__(ByteArray byteArray , IWorldReportServerService serverService)
        {
            int errorCode = byteArray.readDynamicsInt();
            if(ClientRequestErrorHandler__ != null)
            {
                ClientRequestErrorHandler__(errorCode);
            }
            return true;
        }
        
        
        public delegate void ClientRequestErrorDelegate__(int errorCode);
        public static ClientRequestErrorDelegate__ ClientRequestErrorHandler__;
   }

    public interface IWorldReportServerService
    {
        
    }
  
    internal class EnumVillageReportMethods
    {
        
        public const int CLIENT_REPORTSTATUS_HASH = -359375886;

        public const int CLIENT_REQUESTERROR_HASH = 876672191;
    }
    
    public class  VillageReportServerHelper
    {
        public const string SOURCE_HASH = "DE-73-AD-8B-D0-C0-C3-D1-79-25-52-7D-EA-09-09-3A";

        
        public static ByteArray ReportStatus(VillageState status)
        {
            ByteArray byteArray = new ByteArray();
            
            byteArray.writeInt( EnumVillageReportMethods.CLIENT_REPORTSTATUS_HASH );
            byteArray.EncryptKey =  EnumVillageReportMethods.CLIENT_REPORTSTATUS_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
          status.WriteToByteArray(byteArray);
          
          ++ByteArray.globalSeq;
            byteArray.writeInt(byteArray.CRC);
            byteArray.EncryptKey =  0;
            return byteArray;
        }
        
        public static void ReportStatus(VillageState status,ByteArray  byteArray)
        {
            byteArray.Reset();
            byteArray.WriteHeader();
            
            byteArray.writeInt( EnumVillageReportMethods.CLIENT_REPORTSTATUS_HASH );
            byteArray.EncryptKey =  EnumVillageReportMethods.CLIENT_REPORTSTATUS_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
            status.WriteToByteArray(byteArray);
            ++ByteArray.globalSeq;
            byteArray.writeIntNCRC(byteArray.CRC);
            byteArray.EncryptKey =  0;
        }
        
        public static ByteArray ClientRequestFailed__(int reason)
        {
            ByteArray byteArray = new ByteArray();
            byteArray.writeInt( EnumVillageReportMethods.CLIENT_REQUESTERROR_HASH);
            byteArray.EncryptKey =  EnumVillageReportMethods.CLIENT_REQUESTERROR_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
            byteArray.writeDynamicsInt(reason);
            ++ByteArray.globalSeq;
            byteArray.writeIntNCRC(byteArray.CRC);
            byteArray.EncryptKey =  0;
            return byteArray;
        }

        public static bool IntepretMessage(ByteArray byteArray,IVillageReportServerService serverService)
        {
            byteArray.BypassHeader();
            int methodID = byteArray.readInt();
            bool mtdrst__ = false;
            switch(methodID)
            {
              
              case EnumVillageReportMethods.CLIENT_REQUESTERROR_HASH:
                byteArray.EncryptKey =  EnumVillageReportMethods.CLIENT_REQUESTERROR_HASH ;
                byteArray.readDynamicsInt();
                OnClientRequestError__(byteArray , serverService);
                byteArray.EncryptKey = 0;
                return true;
            }
            
            // recover the header
            byteArray.Rewind();
            return false;
        }

        public static String ParseMessage(ByteArray byteArray , ParamedDelegate<String> dumper)
        {
            byteArray.BypassHeader();
            int methodID = byteArray.readInt();
            String result = String.Empty;
            switch(methodID)
            {
                           
            case EnumVillageReportMethods.CLIENT_REQUESTERROR_HASH:
                byteArray.EncryptKey =  EnumVillageReportMethods.CLIENT_REQUESTERROR_HASH ;
                byteArray.readDynamicsInt();
                int reason = byteArray.readDynamicsInt();
                byteArray.EncryptKey = 0;
                return string.Format("Client Request Error {0}" ,reason);
            }
            if(result != String.Empty) dumper(result);
            // recover the header
            byteArray.Rewind();
            return result;
        }

        
        private static bool OnClientRequestError__(ByteArray byteArray , IVillageReportServerService serverService)
        {
            int errorCode = byteArray.readDynamicsInt();
            if(ClientRequestErrorHandler__ != null)
            {
                ClientRequestErrorHandler__(errorCode);
            }
            return true;
        }
        
        
        public delegate void ClientRequestErrorDelegate__(int errorCode);
        public static ClientRequestErrorDelegate__ ClientRequestErrorHandler__;
   }

    public interface IVillageReportServerService
    {
        
    }
  
    internal class EnumPortalReportMethods
    {
        
        public const int CLIENT_REPORTSTATUS_HASH = 407451456;

        public const int CLIENT_REQUESTERROR_HASH = 1256294063;
    }
    
    public class  PortalReportServerHelper
    {
        public const string SOURCE_HASH = "DE-73-AD-8B-D0-C0-C3-D1-79-25-52-7D-EA-09-09-3A";

        
        public static ByteArray ReportStatus(PortalState status)
        {
            ByteArray byteArray = new ByteArray();
            
            byteArray.writeInt( EnumPortalReportMethods.CLIENT_REPORTSTATUS_HASH );
            byteArray.EncryptKey =  EnumPortalReportMethods.CLIENT_REPORTSTATUS_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
          status.WriteToByteArray(byteArray);
          
          ++ByteArray.globalSeq;
            byteArray.writeInt(byteArray.CRC);
            byteArray.EncryptKey =  0;
            return byteArray;
        }
        
        public static void ReportStatus(PortalState status,ByteArray  byteArray)
        {
            byteArray.Reset();
            byteArray.WriteHeader();
            
            byteArray.writeInt( EnumPortalReportMethods.CLIENT_REPORTSTATUS_HASH );
            byteArray.EncryptKey =  EnumPortalReportMethods.CLIENT_REPORTSTATUS_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
            status.WriteToByteArray(byteArray);
            ++ByteArray.globalSeq;
            byteArray.writeIntNCRC(byteArray.CRC);
            byteArray.EncryptKey =  0;
        }
        
        public static ByteArray ClientRequestFailed__(int reason)
        {
            ByteArray byteArray = new ByteArray();
            byteArray.writeInt( EnumPortalReportMethods.CLIENT_REQUESTERROR_HASH);
            byteArray.EncryptKey =  EnumPortalReportMethods.CLIENT_REQUESTERROR_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
            byteArray.writeDynamicsInt(reason);
            ++ByteArray.globalSeq;
            byteArray.writeIntNCRC(byteArray.CRC);
            byteArray.EncryptKey =  0;
            return byteArray;
        }

        public static bool IntepretMessage(ByteArray byteArray,IPortalReportServerService serverService)
        {
            byteArray.BypassHeader();
            int methodID = byteArray.readInt();
            bool mtdrst__ = false;
            switch(methodID)
            {
              
              case EnumPortalReportMethods.CLIENT_REQUESTERROR_HASH:
                byteArray.EncryptKey =  EnumPortalReportMethods.CLIENT_REQUESTERROR_HASH ;
                byteArray.readDynamicsInt();
                OnClientRequestError__(byteArray , serverService);
                byteArray.EncryptKey = 0;
                return true;
            }
            
            // recover the header
            byteArray.Rewind();
            return false;
        }

        public static String ParseMessage(ByteArray byteArray , ParamedDelegate<String> dumper)
        {
            byteArray.BypassHeader();
            int methodID = byteArray.readInt();
            String result = String.Empty;
            switch(methodID)
            {
                           
            case EnumPortalReportMethods.CLIENT_REQUESTERROR_HASH:
                byteArray.EncryptKey =  EnumPortalReportMethods.CLIENT_REQUESTERROR_HASH ;
                byteArray.readDynamicsInt();
                int reason = byteArray.readDynamicsInt();
                byteArray.EncryptKey = 0;
                return string.Format("Client Request Error {0}" ,reason);
            }
            if(result != String.Empty) dumper(result);
            // recover the header
            byteArray.Rewind();
            return result;
        }

        
        private static bool OnClientRequestError__(ByteArray byteArray , IPortalReportServerService serverService)
        {
            int errorCode = byteArray.readDynamicsInt();
            if(ClientRequestErrorHandler__ != null)
            {
                ClientRequestErrorHandler__(errorCode);
            }
            return true;
        }
        
        
        public delegate void ClientRequestErrorDelegate__(int errorCode);
        public static ClientRequestErrorDelegate__ ClientRequestErrorHandler__;
   }

    public interface IPortalReportServerService
    {
        
    }
  
    internal class EnumUpdaterReportMethods
    {
        
        public const int CLIENT_REPORTSTATUS_HASH = 268422801;

        public const int CLIENT_REQUESTERROR_HASH = 1540877354;
    }
    
    public class  UpdaterReportServerHelper
    {
        public const string SOURCE_HASH = "DE-73-AD-8B-D0-C0-C3-D1-79-25-52-7D-EA-09-09-3A";

        
        public static ByteArray ReportStatus(UpdaterState status)
        {
            ByteArray byteArray = new ByteArray();
            
            byteArray.writeInt( EnumUpdaterReportMethods.CLIENT_REPORTSTATUS_HASH );
            byteArray.EncryptKey =  EnumUpdaterReportMethods.CLIENT_REPORTSTATUS_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
          status.WriteToByteArray(byteArray);
          
          ++ByteArray.globalSeq;
            byteArray.writeInt(byteArray.CRC);
            byteArray.EncryptKey =  0;
            return byteArray;
        }
        
        public static void ReportStatus(UpdaterState status,ByteArray  byteArray)
        {
            byteArray.Reset();
            byteArray.WriteHeader();
            
            byteArray.writeInt( EnumUpdaterReportMethods.CLIENT_REPORTSTATUS_HASH );
            byteArray.EncryptKey =  EnumUpdaterReportMethods.CLIENT_REPORTSTATUS_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
            status.WriteToByteArray(byteArray);
            ++ByteArray.globalSeq;
            byteArray.writeIntNCRC(byteArray.CRC);
            byteArray.EncryptKey =  0;
        }
        
        public static ByteArray ClientRequestFailed__(int reason)
        {
            ByteArray byteArray = new ByteArray();
            byteArray.writeInt( EnumUpdaterReportMethods.CLIENT_REQUESTERROR_HASH);
            byteArray.EncryptKey =  EnumUpdaterReportMethods.CLIENT_REQUESTERROR_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
            byteArray.writeDynamicsInt(reason);
            ++ByteArray.globalSeq;
            byteArray.writeIntNCRC(byteArray.CRC);
            byteArray.EncryptKey =  0;
            return byteArray;
        }

        public static bool IntepretMessage(ByteArray byteArray,IUpdaterReportServerService serverService)
        {
            byteArray.BypassHeader();
            int methodID = byteArray.readInt();
            bool mtdrst__ = false;
            switch(methodID)
            {
              
              case EnumUpdaterReportMethods.CLIENT_REQUESTERROR_HASH:
                byteArray.EncryptKey =  EnumUpdaterReportMethods.CLIENT_REQUESTERROR_HASH ;
                byteArray.readDynamicsInt();
                OnClientRequestError__(byteArray , serverService);
                byteArray.EncryptKey = 0;
                return true;
            }
            
            // recover the header
            byteArray.Rewind();
            return false;
        }

        public static String ParseMessage(ByteArray byteArray , ParamedDelegate<String> dumper)
        {
            byteArray.BypassHeader();
            int methodID = byteArray.readInt();
            String result = String.Empty;
            switch(methodID)
            {
                           
            case EnumUpdaterReportMethods.CLIENT_REQUESTERROR_HASH:
                byteArray.EncryptKey =  EnumUpdaterReportMethods.CLIENT_REQUESTERROR_HASH ;
                byteArray.readDynamicsInt();
                int reason = byteArray.readDynamicsInt();
                byteArray.EncryptKey = 0;
                return string.Format("Client Request Error {0}" ,reason);
            }
            if(result != String.Empty) dumper(result);
            // recover the header
            byteArray.Rewind();
            return result;
        }

        
        private static bool OnClientRequestError__(ByteArray byteArray , IUpdaterReportServerService serverService)
        {
            int errorCode = byteArray.readDynamicsInt();
            if(ClientRequestErrorHandler__ != null)
            {
                ClientRequestErrorHandler__(errorCode);
            }
            return true;
        }
        
        
        public delegate void ClientRequestErrorDelegate__(int errorCode);
        public static ClientRequestErrorDelegate__ ClientRequestErrorHandler__;
   }

    public interface IUpdaterReportServerService
    {
        
    }
  
    internal class EnumBattleReportMethods
    {
        
        public const int CLIENT_REPORTSTATUS_HASH = -155195824;

        public const int CLIENT_REQUESTERROR_HASH = 235164469;
    }
    
    public class  BattleReportServerHelper
    {
        public const string SOURCE_HASH = "DE-73-AD-8B-D0-C0-C3-D1-79-25-52-7D-EA-09-09-3A";

        
        public static ByteArray ReportStatus(BattleState status)
        {
            ByteArray byteArray = new ByteArray();
            
            byteArray.writeInt( EnumBattleReportMethods.CLIENT_REPORTSTATUS_HASH );
            byteArray.EncryptKey =  EnumBattleReportMethods.CLIENT_REPORTSTATUS_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
          status.WriteToByteArray(byteArray);
          
          ++ByteArray.globalSeq;
            byteArray.writeInt(byteArray.CRC);
            byteArray.EncryptKey =  0;
            return byteArray;
        }
        
        public static void ReportStatus(BattleState status,ByteArray  byteArray)
        {
            byteArray.Reset();
            byteArray.WriteHeader();
            
            byteArray.writeInt( EnumBattleReportMethods.CLIENT_REPORTSTATUS_HASH );
            byteArray.EncryptKey =  EnumBattleReportMethods.CLIENT_REPORTSTATUS_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
            status.WriteToByteArray(byteArray);
            ++ByteArray.globalSeq;
            byteArray.writeIntNCRC(byteArray.CRC);
            byteArray.EncryptKey =  0;
        }
        
        public static ByteArray ClientRequestFailed__(int reason)
        {
            ByteArray byteArray = new ByteArray();
            byteArray.writeInt( EnumBattleReportMethods.CLIENT_REQUESTERROR_HASH);
            byteArray.EncryptKey =  EnumBattleReportMethods.CLIENT_REQUESTERROR_HASH ;
            byteArray.CRC = 0;
            byteArray.writeDynamicsInt(ByteArray.globalSeq);
            byteArray.writeDynamicsInt(reason);
            ++ByteArray.globalSeq;
            byteArray.writeIntNCRC(byteArray.CRC);
            byteArray.EncryptKey =  0;
            return byteArray;
        }

        public static bool IntepretMessage(ByteArray byteArray,IBattleReportServerService serverService)
        {
            byteArray.BypassHeader();
            int methodID = byteArray.readInt();
            bool mtdrst__ = false;
            switch(methodID)
            {
              
              case EnumBattleReportMethods.CLIENT_REQUESTERROR_HASH:
                byteArray.EncryptKey =  EnumBattleReportMethods.CLIENT_REQUESTERROR_HASH ;
                byteArray.readDynamicsInt();
                OnClientRequestError__(byteArray , serverService);
                byteArray.EncryptKey = 0;
                return true;
            }
            
            // recover the header
            byteArray.Rewind();
            return false;
        }

        public static String ParseMessage(ByteArray byteArray , ParamedDelegate<String> dumper)
        {
            byteArray.BypassHeader();
            int methodID = byteArray.readInt();
            String result = String.Empty;
            switch(methodID)
            {
                           
            case EnumBattleReportMethods.CLIENT_REQUESTERROR_HASH:
                byteArray.EncryptKey =  EnumBattleReportMethods.CLIENT_REQUESTERROR_HASH ;
                byteArray.readDynamicsInt();
                int reason = byteArray.readDynamicsInt();
                byteArray.EncryptKey = 0;
                return string.Format("Client Request Error {0}" ,reason);
            }
            if(result != String.Empty) dumper(result);
            // recover the header
            byteArray.Rewind();
            return result;
        }

        
        private static bool OnClientRequestError__(ByteArray byteArray , IBattleReportServerService serverService)
        {
            int errorCode = byteArray.readDynamicsInt();
            if(ClientRequestErrorHandler__ != null)
            {
                ClientRequestErrorHandler__(errorCode);
            }
            return true;
        }
        
        
        public delegate void ClientRequestErrorDelegate__(int errorCode);
        public static ClientRequestErrorDelegate__ ClientRequestErrorHandler__;
   }

    public interface IBattleReportServerService
    {
        
    }
  
    #endregion    //SECTION_TRANSACTIONS
}
// END OF GENERATED CODE
  