//source signature: [DE-73-AD-8B-D0-C0-C3-D1-79-25-52-7D-EA-09-09-3A]
    // Autogenerated at 2016/3/24 14:25:36.
    // Created by [CodeGenerator Library:1.7.3.2014.04.20.15.19] FOR Server Protocol.
    // Don't manully change this code unless you have to, all changes will be lost next time code is generated.
    // Copyright ideadynamo.com 2008-2012.
    namespace com.tieao.mmo.deamon
    {
    using System;
    using System.Text;
    using System.Xml;
    using System.IO;
    using System.Collections;
    using System.Collections.Generic;
    using com.ideadynamo.foundation;
    using com.ideadynamo.foundation.buffer;
    
    // set com.tieao.mmo.deamon
    #region enumerations
    
    #endregion    //SECTION_ENUM

    #region structures  // use class because struct's un-referenced behavior is not prefered
    
    [Serializable]
    public class WorldState
    {
      public int timestamp;
      public int logons;
      public float sdkresponse;
      public int refills;
      public int refilltotal;
      public int serials;
      public int lastlogontime;
      public int newusers;
      

      public void WriteToByteArray(ByteArray byteArray)
      {
        byteArray.writeDynamicsInt( timestamp);
        byteArray.writeDynamicsInt( logons);
        byteArray.writeFloat( sdkresponse);
        byteArray.writeDynamicsInt( refills);
        byteArray.writeDynamicsInt( refilltotal);
        byteArray.writeDynamicsInt( serials);
        byteArray.writeDynamicsInt( lastlogontime);
        byteArray.writeDynamicsInt( newusers);
        
      }

      public void ReadFromByteArray(ByteArray byteArray)
      {
        timestamp = byteArray.readDynamicsInt();
        logons = byteArray.readDynamicsInt();
        sdkresponse = byteArray.readFloat();
        refills = byteArray.readDynamicsInt();
        refilltotal = byteArray.readDynamicsInt();
        serials = byteArray.readDynamicsInt();
        lastlogontime = byteArray.readDynamicsInt();
        newusers = byteArray.readDynamicsInt();
        
      }
      
      public static WorldState SReadFromByteArray(ByteArray byteArray)
      {
          WorldState elem = new WorldState ();
          elem.ReadFromByteArray(byteArray);
          return elem;
      }
      
      
      public override string ToString()
      {
          StringBuilder sb = new StringBuilder();
          sb.Append("WorldState:{");
          
          sb.AppendFormat(@" timestamp  = ""{0}"",",timestamp );
          
          sb.AppendFormat(@" logons  = ""{0}"",",logons );
          
          sb.AppendFormat(@" sdkresponse  = ""{0}"",",sdkresponse );
          
          sb.AppendFormat(@" refills  = ""{0}"",",refills );
          
          sb.AppendFormat(@" refilltotal  = ""{0}"",",refilltotal );
          
          sb.AppendFormat(@" serials  = ""{0}"",",serials );
          
          sb.AppendFormat(@" lastlogontime  = ""{0}"",",lastlogontime );
          
          sb.AppendFormat(@" newusers  = ""{0}"",",newusers );
          
          sb.Remove(sb.Length - 1, 1);
          sb.Append("}");
          return sb.ToString();
      }
  }
  
    [Serializable]
    public class VillageState
    {
      public int timestamp;
      public int logons;
      public float logonresponse;
      public int paymenttoday;
      

      public void WriteToByteArray(ByteArray byteArray)
      {
        byteArray.writeDynamicsInt( timestamp);
        byteArray.writeDynamicsInt( logons);
        byteArray.writeFloat( logonresponse);
        byteArray.writeDynamicsInt( paymenttoday);
        
      }

      public void ReadFromByteArray(ByteArray byteArray)
      {
        timestamp = byteArray.readDynamicsInt();
        logons = byteArray.readDynamicsInt();
        logonresponse = byteArray.readFloat();
        paymenttoday = byteArray.readDynamicsInt();
        
      }
      
      public static VillageState SReadFromByteArray(ByteArray byteArray)
      {
          VillageState elem = new VillageState ();
          elem.ReadFromByteArray(byteArray);
          return elem;
      }
      
      
      public override string ToString()
      {
          StringBuilder sb = new StringBuilder();
          sb.Append("VillageState:{");
          
          sb.AppendFormat(@" timestamp  = ""{0}"",",timestamp );
          
          sb.AppendFormat(@" logons  = ""{0}"",",logons );
          
          sb.AppendFormat(@" logonresponse  = ""{0}"",",logonresponse );
          
          sb.AppendFormat(@" paymenttoday  = ""{0}"",",paymenttoday );
          
          sb.Remove(sb.Length - 1, 1);
          sb.Append("}");
          return sb.ToString();
      }
  }
  
    [Serializable]
    public class PortalState
    {
      public int timestamp;
      public int logons;
      public float logonresponse;
      

      public void WriteToByteArray(ByteArray byteArray)
      {
        byteArray.writeDynamicsInt( timestamp);
        byteArray.writeDynamicsInt( logons);
        byteArray.writeFloat( logonresponse);
        
      }

      public void ReadFromByteArray(ByteArray byteArray)
      {
        timestamp = byteArray.readDynamicsInt();
        logons = byteArray.readDynamicsInt();
        logonresponse = byteArray.readFloat();
        
      }
      
      public static PortalState SReadFromByteArray(ByteArray byteArray)
      {
          PortalState elem = new PortalState ();
          elem.ReadFromByteArray(byteArray);
          return elem;
      }
      
      
      public override string ToString()
      {
          StringBuilder sb = new StringBuilder();
          sb.Append("PortalState:{");
          
          sb.AppendFormat(@" timestamp  = ""{0}"",",timestamp );
          
          sb.AppendFormat(@" logons  = ""{0}"",",logons );
          
          sb.AppendFormat(@" logonresponse  = ""{0}"",",logonresponse );
          
          sb.Remove(sb.Length - 1, 1);
          sb.Append("}");
          return sb.ToString();
      }
  }
  
    [Serializable]
    public class UpdaterState
    {
      public int timestamp;
      public string andoirdapp;
      public string andoirdres;
      public string iosapp;
      public string iosres;
      

      public void WriteToByteArray(ByteArray byteArray)
      {
        byteArray.writeDynamicsInt( timestamp);
        byteArray.writeUTF( andoirdapp);
        byteArray.writeUTF( andoirdres);
        byteArray.writeUTF( iosapp);
        byteArray.writeUTF( iosres);
        
      }

      public void ReadFromByteArray(ByteArray byteArray)
      {
        timestamp = byteArray.readDynamicsInt();
        andoirdapp = byteArray.readUTF();
        andoirdres = byteArray.readUTF();
        iosapp = byteArray.readUTF();
        iosres = byteArray.readUTF();
        
      }
      
      public static UpdaterState SReadFromByteArray(ByteArray byteArray)
      {
          UpdaterState elem = new UpdaterState ();
          elem.ReadFromByteArray(byteArray);
          return elem;
      }
      
      
      public override string ToString()
      {
          StringBuilder sb = new StringBuilder();
          sb.Append("UpdaterState:{");
          
          sb.AppendFormat(@" timestamp  = ""{0}"",",timestamp );
          
          sb.AppendFormat(@" andoirdapp  = ""{0}"",",andoirdapp );
          
          sb.AppendFormat(@" andoirdres  = ""{0}"",",andoirdres );
          
          sb.AppendFormat(@" iosapp  = ""{0}"",",iosapp );
          
          sb.AppendFormat(@" iosres  = ""{0}"",",iosres );
          
          sb.Remove(sb.Length - 1, 1);
          sb.Append("}");
          return sb.ToString();
      }
  }
  
    [Serializable]
    public class BattleState
    {
      public int timestamp;
      public string currentcount;
      public string maxcount;
      

      public void WriteToByteArray(ByteArray byteArray)
      {
        byteArray.writeDynamicsInt( timestamp);
        byteArray.writeUTF( currentcount);
        byteArray.writeUTF( maxcount);
        
      }

      public void ReadFromByteArray(ByteArray byteArray)
      {
        timestamp = byteArray.readDynamicsInt();
        currentcount = byteArray.readUTF();
        maxcount = byteArray.readUTF();
        
      }
      
      public static BattleState SReadFromByteArray(ByteArray byteArray)
      {
          BattleState elem = new BattleState ();
          elem.ReadFromByteArray(byteArray);
          return elem;
      }
      
      
      public override string ToString()
      {
          StringBuilder sb = new StringBuilder();
          sb.Append("BattleState:{");
          
          sb.AppendFormat(@" timestamp  = ""{0}"",",timestamp );
          
          sb.AppendFormat(@" currentcount  = ""{0}"",",currentcount );
          
          sb.AppendFormat(@" maxcount  = ""{0}"",",maxcount );
          
          sb.Remove(sb.Length - 1, 1);
          sb.Append("}");
          return sb.ToString();
      }
  }
  
    #endregion    //SECTION_STRUCTURE

    #region sequences
    
    #endregion    //SECTION_SEQUENCE

    #region directory
    
    #endregion    //SECTION_DIRECTORY
    }
    // END OF GENERATED CODE
  