//source signature: [D4-D2-43-05-CF-01-AF-B2-92-1F-E1-DE-88-B6-F0-A5]
    // Autogenerated at 2016/3/24 14:25:34.
    // Created by [CodeGenerator Library:1.7.3.2014.04.20.15.19] FOR Server Protocol.
    // Don't manully change this code unless you have to, all changes will be lost next time code is generated.
    // Copyright ideadynamo.com 2008-2012.
    namespace com.tieao.mmo.deamon
    {
    using System;
    using System.Text;
    using System.Xml;
    using System.IO;
    using System.Collections;
    using System.Collections.Generic;
    using com.ideadynamo.foundation;
    using com.ideadynamo.foundation.buffer;
    
    // set com.tieao.mmo.deamon
    #region enumerations
    
    #endregion    //SECTION_ENUM

    #region structures  // use class because struct's un-referenced behavior is not prefered
    
    #endregion    //SECTION_STRUCTURE

    #region sequences
    
    #endregion    //SECTION_SEQUENCE

    #region directory
    
    #endregion    //SECTION_DIRECTORY
    }
    // END OF GENERATED CODE
  