//source signature: [D1-0E-0B-79-C1-4C-AF-B6-23-78-B3-B1-51-E6-FF-7B]
    // Autogenerated at 2017/2/3 21:09:18.
    // Created by [CodeGenerator Library:1.7.3.2014.04.20.15.19] FOR Server Protocol.
    // Don't manully change this code unless you have to, all changes will be lost next time code is generated.
    // Copyright ideadynamo.com 2008-2012.
    namespace com.tieao.mmo.protocol
    {
    using System;
    using System.Text;
    using System.Xml;
    using System.IO;
    using System.Collections;
    using System.Collections.Generic;
    using com.ideadynamo.foundation;
    using com.ideadynamo.foundation.buffer;
    
      using com.tieao.mmo.CustomTypeInProtocol;
    
    // set com.tieao.mmo.protocol
    #region enumerations
    
    #endregion    //SECTION_ENUM

    #region structures  // use class because struct's un-referenced behavior is not prefered
    
    #endregion    //SECTION_STRUCTURE

    #region sequences
    
    #endregion    //SECTION_SEQUENCE

    #region directory
    
    #endregion    //SECTION_DIRECTORY
    }
    // END OF GENERATED CODE
  